[ req ]
default_bits       = 4096
prompt             = no
encrypt_key        = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_ca

[ dn ]
O  = Istio
CN = Root CA

[ v3_ca ]
subjectKeyIdentifier   = hash
basicConstraints       = critical,CA:true,pathlen:1
keyUsage               = critical,digitalSignature,keyCertSign
authorityKeyIdentifier = keyid:always,issuer:always
