apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh
      multiCluster:
        clusterName: primary
      network: network1
      externalIstiod: true
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
