apiVersion: v1
kind: Node
metadata:
  name: kwok-node-0
  annotations:
    kwok.x-k8s.io/node: fake
    node.alpha.kubernetes.io/ttl: "0"
  labels:
    type: kwok
    kubernetes.io/hostname: kwok-node-0
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
status:
  allocatable: { cpu: "32", memory: 256Gi, pods: "256" }
  capacity:    { cpu: "32", memory: 256Gi, pods: "256" }
  nodeInfo: { kubeletVersion: fake }
  phase: Running