apiVersion: apps/v1
kind: Deployment
metadata:
  name: responder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responder
  template:
    metadata:
      labels:
        app: responder
    spec:
      containers:
        - name: responder
          image: responder:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"