apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
        - name: sender
          image: sender:latest
          ports:
            - containerPort: 8080
          env:
            - name: RESPONDER_URL
              value: "PLACEHOLDER"
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
